### ISSUE TITLE
状态检测的代码好像不全吧，眼睛状态检测怎么获得两个返回值呢

### ISSUE THREAD

**Issue by huaxuanHan** [CodingNowPls/SeetaFace64Android#1]

**Comment by huaxuanHan** [comment]
质量检测代码不全，眼睛状态检测怎么获取到两个返回值，麻烦了

**Comment by huaxuanHan** [comment]
切换后置摄像头以后，摄像头是正的，但是左上角显示的人脸是上下倒置的，这个显示我自己反转了，但是人脸比对的过程用到的人脸数据应该还是倒置的，所以一直比对不出数据，把手机上下颠倒一下就能比对出人脸了，到这里我就不知道咋解决了

**Comment by CodingNowPls** [comment]
这个翻转自己可以做适配，眼睛检测的我没有用到，但是里面应该是有api提供的，你直接传值进去，他会给你返回值，然后判断应该就可以了
