### ISSUE TITLE
请问下so库编译前的C++文件怎么获取最新的？

### ISSUE THREAD

**Issue by JakeWoki** [CodingNowPls/SeetaFace64Android#3]
和github上官方的不一样，比如FaceDetector.java里的native不一样，自己改的还是说官方最新的？

**Comment by CodingNowPls** [comment]
自己改的，但是基本跟官方的差不多，如果想要自己改的话，看reademe里面的参考项目，里面有源码，自行修改编译

**Comment by CodingNowPls** [comment]
native方法里面我注释了官方的方法名

**Comment by JakeWoki** [comment]
好的谢谢
