### ISSUE TITLE
在有些设备上摄像头被旋转了90

### ISSUE THREAD

**Issue by huaxuanHan** [CodingNowPls/SeetaFace64Android#5]
在有些设备上摄像头被旋转了90，MOBILE_FACE(EnumCamera.CAMERA_FACING, 0, "手机前置"),这里改成0的话，摄像头画面是正了过来，可是又检测不到人脸，必须把设备横着才能检测到人脸，我又试了改成别的角度，摄像头方向又不对，试了很多种方法，好像不管咋改代码都不行，只有把设备横过来才能检测到人脸，这是为啥呢，能给点思路吗

**Comment by CodingNowPls** [comment]
你可以自己加枚举，然后调试看看到底需要旋转多少
